site_name: Hacknet Pathfinder Documentation
site_dir: docs
docs_dir: mkdocs
site_url: https://arkhist.github.io/Hacknet-Pathfinder/
nav:
    - Pathfinder:
        - Home: index.md
    - Mod Development:
        - Getting started: mod/start.md
        - Ports: mod/ports.md
        - Commands: mod/commands.md
        - Executables: mod/executables.md
        - Computers: mod/computers.md
        - Daemons: mod/daemons.md
        - Actions: mod/actions.md
        - Missions: mod/missions.md
    - Pathfinder Development: 
        - Contributing: contributing.md
theme: readthedocs