site_name: Hacknet Pathfinder Documentation
site_dir: docs
docs_dir: mkdocs
site_url: https://arkhist.github.io/Hacknet-Pathfinder/
nav:
    - Pathfinder:
        - Home: index.md
    - Mod Development:
        - Getting started: mod/start.md
        - Actions: mod/actions.md
        - Administrators: mod/administrators.md
        - Commands: mod/commands.md
        - Daemons: mod/daemons.md
        - Executables: mod/executables.md
        - Missions: mod/missions.md
        - Ports: mod/ports.md
    - Pathfinder Development: 
        - Contributing: contributing.md
    - API:
        - Classes: doxybook/Classes/index.md
        - Namespaces: doxybook/Namespaces/index.md
        - Modules: doxybook/Modules/index.md
        - Files: doxybook/Files/index.md
        - Related Pages: doxybook/Pages/index.md
        - Examples: doxybook/Examples/index.md
theme: readthedocs
markdown_extensions:
    - footnotes
