site_name: Hacknet Pathfinder Documentation
site_dir: docs
docs_dir: mkdocs
site_url: https://arkhist.github.io/Hacknet-Pathfinder/
nav:
    - Pathfinder:
        - Home: index.md
    - Mod Development:
        - Getting started: mod/start.md
        - Actions: mod/actions.md
        - Administrators: mod/administrators.md
        - Commands: mod/commands.md
        - Conditions: mod/conditions.md
        - Daemons: mod/daemons.md
        - Executables: mod/executables.md
        - Missions: mod/missions.md
        - Ports: mod/ports.md
    - Pathfinder Development: 
        - Contributing: contributing.md
    - Hacknet Documentation:
        - GUI: hndocs/gui/README.md
    - Development Guides:
        - GUI Basics: guides/guibasics.md
    - API:
        - Classes: /doxybook/Classes
        - Namespaces: /doxybook/Namespaces
        - Modules: /doxybook/Modules
        - Files: /doxybook/Files
        - Related Pages: /doxybook/Pages
        - Examples: /doxybook/Examples
theme: readthedocs
markdown_extensions:
    - footnotes
