namespace CefInterop
{
    public enum cef_color_model_t
    {
        COLOR_MODEL_UNKNOWN,
        COLOR_MODEL_GRAY,
        COLOR_MODEL_COLOR,
        COLOR_MODEL_CMYK,
        COLOR_MODEL_CMY,
        COLOR_MODEL_KCMY,
        COLOR_MODEL_CMY_K,
        COLOR_MODEL_BLACK,
        COLOR_MODEL_GRAYSCALE,
        COLOR_MODEL_RGB,
        COLOR_MODEL_RGB16,
        COLOR_MODEL_RGBA,
        COLOR_MODEL_COLORMODE_COLOR,
        COLOR_MODEL_COLORMODE_MONOCHROME,
        COLOR_MODEL_HP_COLOR_COLOR,
        COLOR_MODEL_HP_COLOR_BLACK,
        COLOR_MODEL_PRINTOUTMODE_NORMAL,
        COLOR_MODEL_PRINTOUTMODE_NORMAL_GRAY,
        COLOR_MODEL_PROCESSCOLORMODEL_CMYK,
        COLOR_MODEL_PROCESSCOLORMODEL_GREYSCALE,
        COLOR_MODEL_PROCESSCOLORMODEL_RGB,
    }
}
