namespace CefInterop
{
    public enum cef_resultcode_t
    {
        CEF_RESULT_CODE_NORMAL_EXIT,
        CEF_RESULT_CODE_KILLED,
        CEF_RESULT_CODE_HUNG,
        CEF_RESULT_CODE_KILLED_BAD_MESSAGE,
        CEF_RESULT_CODE_GPU_DEAD_ON_ARRIVAL,
        CEF_RESULT_CODE_CHROME_FIRST,
        CEF_RESULT_CODE_MISSING_DATA = 7,
        CEF_RESULT_CODE_UNSUPPORTED_PARAM = 13,
        CEF_RESULT_CODE_PROFILE_IN_USE = 21,
        CEF_RESULT_CODE_PACK_EXTENSION_ERROR = 22,
        CEF_RESULT_CODE_NORMAL_EXIT_PROCESS_NOTIFIED = 24,
        CEF_RESULT_CODE_INVALID_SANDBOX_STATE = 31,
        CEF_RESULT_CODE_CLOUD_POLICY_ENROLLMENT_FAILED = 32,
        CEF_RESULT_CODE_GPU_EXIT_ON_CONTEXT_LOST = 34,
        CEF_RESULT_CODE_NORMAL_EXIT_PACK_EXTENSION_SUCCESS = 36,
        CEF_RESULT_CODE_SYSTEM_RESOURCE_EXHAUSTED = 37,
        CEF_RESULT_CODE_CHROME_LAST = 39,
        CEF_RESULT_CODE_SANDBOX_FATAL_FIRST = 7006,
        CEF_RESULT_CODE_SANDBOX_FATAL_INTEGRITY = CEF_RESULT_CODE_SANDBOX_FATAL_FIRST,
        CEF_RESULT_CODE_SANDBOX_FATAL_DROPTOKEN,
        CEF_RESULT_CODE_SANDBOX_FATAL_FLUSHANDLES,
        CEF_RESULT_CODE_SANDBOX_FATAL_CACHEDISABLE,
        CEF_RESULT_CODE_SANDBOX_FATAL_CLOSEHANDLES,
        CEF_RESULT_CODE_SANDBOX_FATAL_MITIGATION,
        CEF_RESULT_CODE_SANDBOX_FATAL_MEMORY_EXCEEDED,
        CEF_RESULT_CODE_SANDBOX_FATAL_WARMUP,
        CEF_RESULT_CODE_SANDBOX_FATAL_LAST,
    }
}
