name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout Extra Libraries
      uses: actions/checkout@v2
      with:
        repository: Windows10CE/HacknetPluginTemplate
        path: 'template'

    - name: Copy Libraries
      run: |
        copy template/libs/HacknetPathfinder.exe libs/HacknetPathfinder.exe
        copy template/libs/FNA.dll libs/FNA.dll

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Build Projects
      run: dotnet build -c release /p:DisableBepInExHacknetPrepareForBuild=true

    - name: Create Release Directory
      run: |
        mkdir Release
        mkdir Release/BepInEx
        mkdir Release/BepInEx/core
        mkdir Release/BepInEx/plugins
        mkdir Release/BepInEx/config
        copy PathfinderAPI/bin/Release/PathfinderAPI.dll Release/BepInEx/plugins/
        copy PathfinderUpdater/bin/Release/PathfinderUpdater.dll Release/BepInEx/plugins/
        copy BepInEx.Hacknet/bin/Release/* Release/BepInEx/core/
        copy libs/BepInEx.cfg Release/BepInEx/config/BepInEx.cfg
        copy PathfinderPatcher/bin/Release/PathfinderPatcher.exe Release/PathfinderPatcher.exe
        copy libs/Mono.Cecil.dll Release/Mono.Cecil.dll
        copy Linux/intercept.so Release/intercept.so
        copy Linux/StartPathfinder.sh Release/StartPathfinder.sh

    - name: Create Release ZIP
      uses: TheDoctor0/zip-release@0.6.0
      with:
        type: 'zip'
        filename: 'Pathfinder.Release.zip'
        directory: 'Release'

    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.9'

    - name: Install PyInstaller
      run: python -m pip install pyinstaller requests

    - name: Build Installer EXE
      run: |
        cd PathfinderInstaller
        pyinstaller --onefile --noconsole PathfinderInstaller.py
        cd ..

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Release/Pathfinder.Release.zip
          PathfinderInstaller/dist/PathfinderInstaller.exe
          PathfinderInstaller/PathfinderInstaller.py

  upload-linux-installer-binary:

    needs: build-windows
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.9'

    - name: Install PyInstaller
      run: python -m pip install pyinstaller requests

    - name: Build Linux Installer Binary
      run: |
        cd PathfinderInstaller
        pyinstaller --onefile --noconsole PathfinderInstaller.py
        mv ./dist/PathfinderInstaller ./dist/PathfinderInstaller.x86_64
        chmod +x ./dist/PathfinderInstaller.x86_64
        cd ..

    - name: Upload Linux Installer Binary
      uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./PathfinderInstaller/dist/PathfinderInstaller.x86_64"]'